config/routes.rb
Rails.application.routes.draw do
  root 'sessions#login'
  get 'articles/search', to: 'articles#search', as: :search_page
  get 'sessions/login', to: 'sessions#login', as: :new_session
  post 'sessions/login', to: 'sessions#check'
  delete 'sessions/logout', to: 'sessions#destroy', as: :destroy_session
  resources:categories, only:[:show]
  resources :users, only:[:new, :create, :show]
  resources :articles, only:[:new, :create, :show, :index]
  resources :votes, only:[:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'authorid'
  has_many :votes
  has_many :relations, foreign_key: 'article_id'
  has_many :categories, through: :relations, source: 'categorie'
  validates :title, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 100 }
  validates :text, presence: true, length: { minimum: 200 }
  validates :image, presence: true

  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png']

  def self.search(search)
    @articles = if search
                  search = search.downcase
                  Article.where('lower(title) LIKE ?', "%#{search}%")
                else
                  Article.all.ordered_articles
                end
  end

  def number_of_votes
    votes.count
  end

  def self.last_art(param)
    Article.find(param)
  end

  scope :ordered_articles, -> { order(created_at: :desc) }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :current_user
  def index
    @articles = Article.all
    @popular_article = Vote.popular_article
    @categories = Categorie.priority_ordered
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.authorid = current_user.id
    tag_ids = params[:tag_ids]
    if tag_ids.nil?
      tag_ids = []
      tag_ids << 1
    end
    if @article.save && !@article.image.nil?
      tag_ids.each do |t|
        @cat = Categorie.find(t)
        @ac = Relation.create(article_id: @article.id, category_id: @cat.id)
        @ac.save
      end
      redirect_to article_path(id: @article.id)
      flash.notice = 'Article saved'
    else
      render :new
      flash.notice = 'Error article not saved'
    end
  end

  def show
    @article = Article.last_art(params[:id])
  end

  def search
    @articles = Article.search(params[:search]).paginate(page: params[:page], per_page: 5)
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :image)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def image_art(popular_article)
    if !popular_article.nil?
      popular_article.image.url
    else
      asset_path('bg.jpg')
    end
  end

  def tilte_art(popular_article)
    if !popular_article.nil?
      popular_article.title
    else
      'No article'
    end
  end

  def text_art(popular_article)
    if !popular_article.nil?
      popular_article.text.truncate(200)
    else
      'No article'
    end
  end

  def image_cat(category)
    if !category.articles.last.nil?
      category.articles.last.image.url
    else
      asset_path('bg.jpg')
    end
  end

  def art_cat(category)
    if !category.articles.last.nil?
      category.articles.last.title
    else
      'No article'
    end
  end

  def path_art(popular_article)
    if !popular_article.nil?
      article_path(id: popular_article.id)
    else
      '#'
    end
  end

  def path_art_cat(category)
    if !category.articles.last.nil?
      article_path(id: category.articles.last.id)
    else
      '#'
    end
  end
end

app/views/articles/_footer.html.erb
<footer>

  <div class="footer-bottom">
    <div class="logo">
      <img src="<%=asset_path('eagles.ico')%>" alt="">
    </div>
    <div>
      <span> Privacy Policy Terms and Conditions ©</span>
      <span>Copyright 2022. All rights reserved</span>
    </div>
    <div>
      contact us
    </div>

  </div>
</footer>

app/views/articles/_header.html.erb
<div class="header">
  <div class="logo">
    <img src="<%=asset_path('eagles.ico')%>" alt="logo">
  </div>
  <div class="menu">
    <ul>
      <li><%= link_to "HOME", articles_path%></li>
      <li><%= link_to "NEW", new_article_path%></li>
      <li><%= link_to "SEARCH", search_page_path%></li>
      <li><%= link_to "TRAIN", category_path(id: 4), method: :get%></li>
      <li><%= link_to "CAR", category_path(id: 3), method: :get%></li>
      <li><%= link_to "RADIO", category_path(id: 2), method: :get%></li>
      <li><%= link_to "TV", category_path(id: 1), method: :get%></li>
    </ul>

  </div>
  <div class="exit">
    <%= @current_user.name %> | <%= link_to "LOGOUT", destroy_session_path, data:{method: :delete} %>
  </div>

</div>

app/views/articles/index.html.erb
<%= render partial: 'header' %>

<div class="full" style="background-image: url(<%= image_art(@popular_article)%>);">
  <ul>
    <li><%= link_to tilte_art(@popular_article), path_art(@popular_article), method: :get, class:"top-title"%></li>
    <li class="top-text"><%= text_art(@popular_article)%></li>
  </ul>
</div>

<div class="categorie-cont">
  <% @categories.each do |category| %>
    <div class="categorie" style="background-image: url(<%= image_cat(category)%>);">
      <ul>
        <li><%= link_to category.name, category_path(id: category.id), method: :get, class:"author"%></li>
        <li><%= link_to art_cat(category), path_art_cat(category), method: :get, class:"top-title"%></li>
      </ul>
    </div>
  <% end %>
</div>

<%= render partial: 'footer' %>

app/views/articles/new.html.erb
<%= render partial: 'header' %>

<div class="container">
  <%= form_for(@article, html: {multipart: true}) do |f| %>
<h1>Write an article</h1>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li class="warning"><%= error %></li>
  <% end %>
  </ul>

    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title, class:'input_form' %>
    </p>

    <p>
      <%= f.label :text %><br />
      <%= f.text_area :text %>
    </p>

    <p class="space">
      <%= f.label :image, "Attach an Image" %><br />
      <%= f.file_field :image %>
    </p>


    <p class="space">
      Categories: (Choose one categorie)<br />

      <input type="checkbox" name="tag_ids[]" value="1" />Tv
      <input type="checkbox" name="tag_ids[]" value="2" />Radio
      <input type="checkbox" name="tag_ids[]" value="3" />Car
      <input type="checkbox" name="tag_ids[]" value="4" />Train
    </p>


    <div class="proceed_button">
      <%= button_tag(type: 'submit', class: "proceed", id: 'validForm') do%>
        <span>Create Article</span>
      <% end %>
    </div>
  <% end %>

</div>

<%= render partial: 'footer' %>

app/views/articles/search.html.erb
<%= render partial: 'header' %>
<div class="log-div">
  <%= form_tag(search_page_path, :method => "get", class: "form") do %>
    <div class="recherche">
      <%= text_field_tag :search, params[:search], class:"input_form", placeholder: "Search articles" %>
      <%= submit_tag "Search", class:'search' %>
    </div>
  <% end %>
</div>

<hr />
<table class="blueTable">
  <thead>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
  </thead>
  <tfoot>
    <tr>
    <td colspan="4">
    <div class="links"><%= will_paginate @articles %></div>
    </td>
    </tr>
</tfoot>
  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(id: article.id), method: :get%></td>
      <td class="word-wrap"><%= article.text.truncate(100) %></td>
    </tr>
  </tbody>
  <% end %>
<%= render partial: 'footer' %>

app/views/articles/show.html.erb
<%= render partial: 'header' %>

  <p class="warning margin-top"><%= flash.notice %></p>
  <div class="cont-art">
    <div class="art-image" style="background-image: url(<%= @article.image.url %>);">
    </div>
    <div class="art">
      <ul>
        <li> <a href="#" class="art-title"><%= @article.title %></a></li>
        <li class="word-wrap"><%= @article.text%>
        </li>
        <li>Author: <span class="author"><%= @article.author.name %></span></li>
        <li><%= link_to 'vote', votes_path(article_id: @article.id), method: :post, class: 'but'%>
        <span class='vote'> (<%= @article.number_of_votes %>)</span> </li>
      </ul>
    </div>
</div>
<div class="bottom">
</div>

<%= render partial: 'footer' %>