config/routes.rb
Rails.application.routes.draw do
  root 'sessions#login'
  get 'articles/search', to: 'articles#search', as: :search_page
  get 'sessions/login', to: 'sessions#login', as: :new_session
  post 'sessions/login', to: 'sessions#check'
  delete 'sessions/logout', to: 'sessions#destroy', as: :destroy_session
  resources:categories, only:[:show]
  resources :users, only:[:new, :create, :show]
  resources :articles, only:[:new, :create, :show, :index]
  resources :votes, only:[:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, class_name: 'Article', foreign_key: 'authorid'
  has_many :votes
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 50 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signin
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:auth] = @user.id
      redirect_to articles_path
      flash.notice = "User '#{@user.name}' Saved!"
    else
      render :new
      flash.notice = "User '#{@user.name}'Error: Not Saved!"
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="log">
  <%= form_for @user, html: {class:'box'} do |f| %>
  <h1>Register</h1>
  <p class="warning"><%= flash.notice %></p>
  <ul>
    <% @user.errors.full_messages.each do |error| %>
      <li class="warning"><%= error %></li>
    <% end %>
  </ul>

    <p>
      <%= f.text_field :name, placeholder: 'Name' ,class:"input_form"%>
    </p>
    <div class="proceed_button">
      <%= f.submit "Save", class:'proceed' %>
      <%= link_to 'Log in', new_session_path(), class:"register" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>